repos:
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--strict]
        additional_dependencies:
          - "pydantic"
          - "sqlalchemy"
          - "pytest"
          - "pytest_asyncio"
          - "fastapi"
          - "dependency_injector"
          - "sqladmin"
          - "alembic"
          - "aio-pika"
          - "python-dotenv"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix]
        exclude: "src"
