"""initial migration

Revision ID:9db626d0eb84
Revises:
Create Date:2022-09-26 14:54:07.075092

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9db626d0eb84"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("pk_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("pk_id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
